/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:7b394344-e7bb-481a-be03-2fae5d4efcc5",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_OGdmLSGx4",
    "aws_user_pools_web_client_id": "j35o7eo3fil3k2j21f3d9nasc",
    "oauth": {}
};


export default awsmobile;
